<?php
/**
 * Created by PhpStorm.
 * User: domoniquedixon
 * Date: 3/3/16
 * Time: 5:38 AM
 */



require 'vendor/autoload.php';
require_once('config.php');
require 'auth.php';
require_once ('language.php');

global $current_user;
global $message;

$loader = new Twig_Loader_Filesystem('templates');

$twig = new Twig_Environment($loader);
$home = $twig->loadTemplate('initial.twig');

echo $home->render(array(
    'welcome' => $message["INDEX_WELCOME"],
    'para_1' => $message["INDEX_PARA_1"],
    'progress' => $message['INDEX_PROGRESS'],
    'section' => $message['INDEX_QUESTION_TITLE'],
    'question_1_title' => $message['INDEX_QUESTION_1_TITLE'],
    'question_2_title' => $message['INDEX_QUESTION_2_TITLE'],
    'question_2_option_1' => $message['INDEX_QUESTION_2_OPTION_1'],
    'question_2_option_2' => $message['INDEX_QUESTION_2_OPTION_2'],
    'question_2_option_3' => $message['INDEX_QUESTION_2_OPTION_3'],
    'question_2_option_4' => $message['INDEX_QUESTION_2_OPTION_4'],
    'backward' => $message['INDEX_BACKWARD'],
    'forward' => $message['INDEX_FORWARD'],
    'dominantHandQuestion' => $message['INDEX_dominantHandQuestion'],
    'dominantHandLeft' => $message['INDEX_dominantHandLeft'],
    'dominantHandRight' => $message['INDEX_dominantHandRight'],
    'dominantHandWriting' => $message['INDEX_dominantHandWriting'],
    'dominantHandDrawing' => $message['INDEX_dominantHandDrawing'],
    'dominantHandBallThrowing' => $message['INDEX_dominantHandBallThrowing'],
    'dominantHandScissors' => $message['INDEX_dominantHandScissors'],
    'dominantHandToothbrush' => $message['INDEX_dominantHandToothbrush'],
    'dominantHandKnifeCutting' => $message['INDEX_dominantHandKnifeCutting'],
    'dominantHandSpoon' => $message['INDEX_dominantHandSpoon'],
    'dominantHandBroom' => $message['INDEX_dominantHandBroom'],
    'dominantHandMatchStrike' => $message['INDEX_dominantHandMatchStrike'],
    'dominantHandBoxLid' => $message['INDEX_dominantHandBoxLid'],
    'raceQuestion1' => $message['INDEX_raceQuestion1'],
    'raceQuestion1a' => $message['INDEX_raceQuestion1a'],
    'raceQuestion1b' => $message['INDEX_raceQuestion1b'],
    'raceQuestion1c' => $message['INDEX_raceQuestion1c'],
    'raceQuestion1d' => $message['INDEX_raceQuestion1d'],
    'raceQuestion1e' => $message['INDEX_raceQuestion1e'],
    'raceQuestion1f' => $message['INDEX_raceQuestion1f'],
    'raceQuestion1g' => $message['INDEX_raceQuestion1g'],
    'raceQuestion2' => $message['INDEX_raceQuestion2'],
    'raceQuestion2a' => $message['INDEX_raceQuestion2a'],
    'raceQuestion2b' => $message['INDEX_raceQuestion2b'],
    'raceQuestion2c' => $message['INDEX_raceQuestion2c'],
    'raceQuestion2d' => $message['INDEX_INDEX_raceQuestion2d'],
    'raceQuestion2e' => $message['INDEX_raceQuestion2e'],
    'maritalQuestion1' => $message['INDEX_maritalQuestion1'],
    'maritalQuestion1a' => $message['INDEX_maritalQuestion1a'],
    'maritalQuestion1b' => $message['INDEX_maritalQuestion1b'],
    'maritalQuestion2' => $message['INDEX_maritalQuestion2'],
    'years' => $message['INDEX_years'],
    'months' => $message['INDEX_months'],
    'maritalQuestionPartnerLabel' => $message['INDEX_maritalQuestionPartnerLabel'],
    'maritalQuestion3' => $message['INDEX_maritalQuestion3'],
    'maritalQuestion4' => $message['INDEX_maritalQuestion4'],
    'maritalSeperated' => $message['INDEX_martialQuestionSeperated'],
    'maritalQuestion5' => $message['INDEX_maritalQuestion5'],
    'maritalQuestion6' => $message['INDEX_maritalQuestion6'],
    'yes' => $message['INDEX_yes'],
    'no' => $message['INDEX_no'],
    'maritalQuestion7' => $message['INDEX_maritalQuestion7'],
    'residenceLive' => $message['INDEX_residenceLive'],
    'city' => $message['INDEX_city'],
    'state' => $message['INDEX_state'],
    'country' => $message['INDEX_country'],
    'residenceInhabitants' => $message['INDEX_residenceInhabitants'],
    'residenceInhabitants1' => $message['INDEX_residenceInhabitants1'],
    'residenceInhabitants2' => $message['INDEX_residenceInhabitants2'],
    'residenceInhabitants3' => $message['INDEX_residenceInhabitants3'],
    'residenceDescribe' => $message['INDEX_residenceDescribe'],
    'residenceRural' => $message['INDEX_residenceRural'],
    'residenceIntermediate' => $message['INDEX_residenceIntermediate'],
    'residenceUrban' => $message['INDEX_residenceUrban'],
    'occupation1' => $message['INDEX_occupation1'],
    'occupation1a' => $message['INDEX_occupation1a'],
    'occupation1b' => $message['INDEX_occupation1b'],
    'occupation1c' => $message['INDEX_occupation1c'],
    'occupation1' => $message['INDEX_occupation1d'],
    'occupation2' => $message['INDEX_occupation2'],
    'occupation2a' => $message['INDEX_occupation2a'],
    'occupation2b' => $message['INDEX_occupation2b'],
    'occupation2c' => $message['INDEX_occupation2c'],
    'occupation2d' => $message['INDEX_occupation2d'],
    'occupation3' => $message['INDEX_occupation3'],
    'occupation3a' => $message['INDEX_occupation3a'],
    'occupation3b' => $message['INDEX_occupation3b'],
    'occupation3c' => $message['INDEX_occupation3c'],
    'occupation3d' => $message['INDEX_occupation3d'],
    'occupation4' => $message['INDEX_occupation4'],
    'occupation4a' => $message['INDEX_occupation4a'],
    'occupation4b' => $message['INDEX_occupation4b'],
    'occupation5' => $message['INDEX_occupation5'],
    'occupation5a' => $message['INDEX_occupation5a'],
    'occupation5b' => $message['INDEX_occupation5b'],
    'occupation5c' => $message['INDEX_occupation5c'],
    'occupation5d' => $message['INDEX_occupation5d'],
    'occupation5e' => $message['INDEX_occupation5e'],
    'occupation5f' => $message['INDEX_occupation5f'],
    'occupation5g' => $message['INDEX_occupation5g'],
    'occupation5h' => $message['INDEX_occupation5h'],
    'occupation5i' => $message['INDEX_occupation5i'],
    'occupation5j' => $message['INDEX_occupation5j'],
    'occupation5k' => $message['INDEX_occupation5k'],
    'occupation5l' => $message['INDEX_occupation5l'],
    'occupation5m' => $message['INDEX_occupation5m'],
    'occupation5n' => $message['INDEX_occupation5n'],
    'occupation5o' => $message['INDEX_occupation5o'],
    'occupation5p' => $message['INDEX_occupation5p'],
    'occupation5q' => $message['INDEX_occupation5q'],
    'occupation5r' => $message['INDEX_occupation5r'],
    'occupation5s' => $message['INDEX_occupation5s'],
    'occupation5t' => $message['INDEX_occupation5t'],
    'occupation5u' => $message['INDEX_occupation5u'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],
    '' => $message['INDEX_'],




));
